<!-- BEGIN: FOOTER -->

	</div>
</div>
<div id="footer" class="container">
	<div class="floatright">
		Generated by <a href="http://cotonti.com" target="blank">CMF Cotonti</a><br/>
		Powered by <a href="http://cmsworks.ru" target="blank">CMSWorks.ru</a>
	</div>
	&copy; {PHP.sys.now|cot_date('Y', $this)} {PHP.cfg.maintitle}
</div>

<script type="text/javascript" src="themes/{PHP.theme}/bootstrap/js/bootstrap.min.js"></script>
{FOOTER_RC}
</body>
</html>
<!-- END: FOOTER -->
